export const pokemonDetails = [
    {id: 1, name: "bulbasaur", details: "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger."},
    {id: 2, name: "ivysaur", details: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs."},
    {id: 3, name: "venusaur", details:  "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight."},
    {id: 4, name: "charmander", details: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail."},
    {id: 5, name: "charmeleon", details: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws."},
    {id: 6, name: "charizard", details:  "It spits fire that is hot enough to melt boulders. It may cause forest fires by blowing flames."},
    {id: 7, name: "squirtle", details: "When it retracts its long neck into its shell, it squirts out water with vigorous force."},
    {id: 8, name: "wartortle", details: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old."},
    {id: 9, name: "blastoise", details: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell."},
    {id: 10, name: "caterpie", details: "For protection, it releases a horrible stench from the antenna on its head to drive away enemies."},
    {id: 11, name: "metapod", details: "It is waiting for the moment to evolve. At this stage, it can only harden, so it remains motionless to avoid attack."},
    {id: 12, name: "butterfree", details: "In battle, it flaps its wings at great speed to release highly toxic dust into the air."},
    {id: 13, name: "weedle", details: "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves."},
    {id: 14, name: "kakuna", details: "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy."},
    {id: 15, name: "beedrill", details: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly."},
    {id: 16, name: "pidgey", details: "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back."},
    {id: 17, name: "pidgeotto", details: "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey."},
    {id: 18, name: "pidgeot", details: "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons."},
    {id: 19, name: "rattata", details: "Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area."},
    {id: 20, name: "raticate", details: "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey."},
    {id: 21, name: "spearow", details: "Inept at flying high. However, it can fly around very fast to protect its territory."},
    {id: 22, name: "fearow", details: "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly."},
    {id: 23, name: "ekans", details: "The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest."},
    {id: 24, name: "arbok", details: "The frightening patterns on its belly have been studied. Six variations have been confirmed."},
    {id: 25, name: "pikachu", details: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy."},
    {id: 26, name: "raichu", details: "Its long tail serves as a ground to protect itself from its own high-voltage power."},
    {id: 27, name: "sandshrew", details: "It loves to bathe in the grit of dry, sandy areas. By sand bathing, the Pokémon rids itself of dirt and moisture clinging to its body."},
    {id: 28, name: "sandslash", details: "The drier the area Sandslash lives in, the harder and smoother the Pokémon’s spikes will feel when touched."},
    {id: 29, name: "nidoran-f", details: "Females are more sensitive to smells than males. While foraging, they’ll use their whiskers to check wind direction and stay downwind of predators."},
    {id: 30, name: "nidorina", details: "The horn on its head has atrophied. It’s thought that this happens so Nidorina’s children won’t get poked while their mother is feeding them."},
    {id: 31, name: "nidoqueen", details: "Nidoqueen is better at defense than offense. With scales like armor, this Pokémon will shield its children from any kind of attack."},
    {id: 32, name: "nidoran-m", details: "The horn on a male Nidoran’s forehead contains a powerful poison. This is a very cautious Pokémon, always straining its large ears."},
    {id: 33, name: "nidorino", details: "With a horn that’s harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone."},
    {id: 34, name: "nidoking", details: "When it goes on a rampage, it’s impossible to control. But in the presence of a Nidoqueen it’s lived with for a long time, Nidoking calms down."},
    {id: 35, name: "clefairy", details: "It is said that happiness will come to those who see a gathering of Clefairy dancing under a full moon."},
    {id: 36, name: "clefable", details: "A timid fairy Pokémon that is rarely seen, it will run and hide the moment it senses people."},
    {id: 37, name: "vulpix", details: "While young, it has six gorgeous tails. When it grows, several new tails are sprouted."},
    {id: 38, name: "ninetales", details: "It is said to live 1,000 years, and each of its tails is loaded with supernatural powers."},
    {id: 39, name: "jigglypuff", details: "Jigglypuff has top-notch lung capacity, even by comparison to other Pokémon. It won’t stop singing its lullabies until its foes fall asleep."},
    {id: 40, name: "wigglytuff", details: "The more air it takes in, the more it inflates. If opponents catch it in a bad mood, it will inflate itself to an enormous size to intimidate them."},
    {id: 41, name: "zubat", details: "It emits ultrasonic waves from its mouth to check its surroundings. Even in tight caves, Zubat flies around with skill."},
    {id: 42, name: "golbat", details: "It loves to drink other creatures’ blood. It’s said that if it finds others of its kind going hungry, it sometimes shares the blood it’s gathered."},
    {id: 43, name: "oddish", details: "If exposed to moonlight, it starts to move. It roams far and wide at night to scatter its seeds."},
    {id: 44, name: "gloom", details: "Its pistils exude an incredibly foul odor. The horrid stench can cause fainting at a distance of 1.25 miles."},
    {id: 45, name: "vileplume", details: "It has the world’s largest petals. With every step, the petals shake out heavy clouds of toxic pollen."},
    {id: 46, name: "paras", details: "Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition."},
    {id: 47, name: "parasect", details: "The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking."},
    {id: 48, name: "venonat", details: "Its large eyes act as radar. In a bright place, you can see that they are clusters of many tiny eyes."},
    {id: 49, name: "venomoth", details: "The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact."},
    {id: 50, name: "diglett", details: "If a Diglett digs through a field, it leaves the soil perfectly tilled and ideal for planting crops."},
    {id: 51, name: "dugtrio", details: "A team of Diglett triplets. It triggers huge earthquakes by burrowing 60 miles underground."},
    {id: 52, name: "meowth", details: "It loves to collect shiny things. If it’s in a good mood, it might even let its Trainer have a look at its hoard of treasures."},
    {id: 53, name: "persian", details: "Getting this prideful Pokémon to warm up to you takes a lot of effort, and it will claw at you the moment it gets annoyed."},
    {id: 54, name: "psyduck", details: ""},
    {id: 55, name: "golduck", details: ""},
    {id: 56, name: "mankey", details: ""},
    {id: 57, name: "primeape", details: ""},
    {id: 58, name: "growlithe", details: ""},
    {id: 59, name: "arcanine", details: ""},
    {id: 60, name: "poliwag", details: ""},
    {id: 61, name: "poliwhirl", details: ""},
    {id: 62, name: "poliwrath", details: ""},
    {id: 63, name: "abra", details: ""},
    {id: 64, name: "kadabra", details: ""},
    {id: 65, name: "alakazam", details: ""},
    {id: 66, name: "machop", details: ""},
    {id: 67, name: "machoke", details: ""},
    {id: 68, name: "machamp", details: ""},
    {id: 69, name: "bellsprout", details: ""},
    {id: 70, name: "weepinbell", details: ""},
    {id: 71, name: "victreebel", details: ""},
    {id: 72, name: "tentacool", details: ""},
    {id: 73, name: "tentacruel", details: ""},
    {id: 74, name: "geodude", details: ""},
    {id: 75, name: "graveler", details: ""},
    {id: 76, name: "golem", details: ""},
    {id: 77, name: "ponyta", details: ""},
    {id: 78, name: "rapidash", details: ""},
    {id: 79, name: "slowpoke", details: ""},
    {id: 80, name: "slowbro", details: ""},
    {id: 81, name: "magnemite", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},
    {id: , name: "", details: ""},



]